version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MUSER?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASS?Variable not set}
      MONGO_INITDB_DATABASE: ${MDB?Variable not set}
    volumes:
      - mongo-data:/var/lib/mongodb
    networks:
      - lumia-backend
    deploy:
      placement:
        constraints:
          - node.labels.mongo.db-data == true
networks:
  lumia-backend:
    external: true
volumes:
  mongo-data:
    driver: local