version: '3.3'

services:
  mongood:
    image: ghcr.io/renzholy/mongood:latest
    restart: always
    networks:
      - lumia-backend
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.mongo.db-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.mongood-auth.basicauth.users=${MGUSER?Variable not set}:${MGHASHED?Variable not set}
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        - traefik.http.routers.mongood-http.rule=Host(`${MGDOMAIN?Variable not set}`)
        - traefik.http.routers.mongood-http.entrypoints=http
        - traefik.http.routers.mongood-http.middlewares=https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        - traefik.http.routers.mongood-https.rule=Host(`${MGDOMAIN?Variable not set}`)
        - traefik.http.routers.mongood-https.entrypoints=https
        - traefik.http.routers.mongood-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.mongood-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        - traefik.http.routers.mongood-https.middlewares=mongood-auth
        # PORT setting
        - traefik.http.services.mongood.loadbalancer.server.port=3000
networks:
  lumia-backend:
    external: true
  traefik-public:
    external: true